name: Node CI 

on: [push]

jobs:
 buildAndtest:
  runs-on: ubuntu-latest
  steps:
   - name : checkout repository 
     uses: actions/checkout@v6  
   - name: npm install , build and test
     run: |
       npm install
       npm run build --if-present
       npm test --if-present
   - name: Upload artifact for deployment job
     uses: actions/upload-artifact@v4
     with:
       name: node-app-artifact
       path: |
         dist
         !dist/**/*.md
   - name: Archive code coverage report
     uses: actions/upload-artifact@v4
     with:
        name: code-coverage-report
        path: output/test/code-coverage.html # Adjust this path to where your coverage report is generated