name: Sample Workflow

on: 
    workflow_dispatch

env:
  sample_env_variable_workflow: "This is a sample environment variable"

jobs:
 sample_job:
  runs-on: ubuntu-latest  
  env:
    sample_env_variable_job: "This is a sample environment variable"

  steps:
  - name: check environment variable 
    run: |
        echo "result::sucess" 
        echo "output-name=$sample_env_variable_workflow" >> $GITHUB_OUTPUT
    env:
      sample_env_variable_step: "This is a sample environment variable"
  
 example-yaml:
  env: &env_vars #define anchor on first use
   Node_ENV: "development"
   DATABASE_URL: "postgres://user:password@localhost:5432/mydatabase"
  runs-on: ubuntu-latest
  steps:
    - run: |
        echo "Node_ENV: ${{ env.Node_ENV }}"
  
 example-yaml-2:
  env: *env_vars #reference anchor on subsequent use
  runs-on: ubuntu-latest
  steps:
    - run: | 
        echo "DATABASE_URL: ${{ env.DATABASE_URL }}"